In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
## Define the Vocabulary size
voc_size = 10000

In [15]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr


[[2913, 2324, 5004, 8969],
 [2913, 2324, 5004, 7055],
 [2913, 767, 5004, 3209],
 [1230, 1244, 6380, 2574, 7035],
 [1230, 1244, 6380, 2574, 505],
 [9786, 2913, 1598, 5004, 5892],
 [1713, 8010, 6445, 2574]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding, Input
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [27]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2913 2324 5004 8969]
 [   0    0    0    0 2913 2324 5004 7055]
 [   0    0    0    0 2913  767 5004 3209]
 [   0    0    0 1230 1244 6380 2574 7035]
 [   0    0    0 1230 1244 6380 2574  505]
 [   0    0    0 9786 2913 1598 5004 5892]
 [   0    0    0    0 1713 8010 6445 2574]]


In [28]:
## Feature representation
dim = 10

In [36]:
from tensorflow.keras.layers import Embedding, Input

model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [38]:

model.summary()


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step


array([[[-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [ 0.00250404,  0.01614083,  0.04514695, -0.02491062,
         -0.04849446, -0.00693469,  0.03930027, -0.04110726,
          0.01977235, -0.00020825],
        [ 0.00281967, -0.01772197,  0.02069818,  0.00838353,
         -0.04858829,  0.02927313, -0.03070157,  0.01226483,
         -0.04397035, -0.01450436],
        [-0.01209227, -0.00210125,  0.00194104,  0.0

In [40]:
embedded_docs[0]

array([   0,    0,    0,    0, 2913, 2324, 5004, 8969])

In [ ]:
import numpy as np

model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [-0.04443955, -0.02063769,  0.0411811 ,  0.03747911,
          0.04074993,  0.03651533, -0.04321876, -0.04918453,
          0.04841261, -0.03875927],
        [ 0.00250404,  0.01614083,  0.04514695, -0.02491062,
         -0.04849446, -0.00693469,  0.03930027, -0.04110726,
          0.01977235, -0.00020825],
        [ 0.00281967, -0.01772197,  0.02069818,  0.00838353,
         -0.04858829,  0.02927313, -0.03070157,  0.01226483,
         -0.04397035, -0.01450436],
        [-0.01209227, -0.00210125,  0.00194104,  0.0