In [76]:
from tensorflow.keras.preprocessing.text import one_hot

In [77]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [78]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [79]:
## Define the Vocabulary size
voc_size = 10000

In [80]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [81]:
## One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr


[[7957, 3175, 1748, 2463],
 [7957, 3175, 1748, 7534],
 [7957, 8249, 1748, 418],
 [743, 724, 6819, 9194, 3068],
 [743, 724, 6819, 9194, 1575],
 [1977, 7957, 6497, 1748, 934],
 [9104, 9839, 9950, 9194]]

In [82]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding, Input
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [83]:
import numpy as np

In [84]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7957 3175 1748 2463]
 [   0    0    0    0 7957 3175 1748 7534]
 [   0    0    0    0 7957 8249 1748  418]
 [   0    0    0  743  724 6819 9194 3068]
 [   0    0    0  743  724 6819 9194 1575]
 [   0    0    0 1977 7957 6497 1748  934]
 [   0    0    0    0 9104 9839 9950 9194]]


In [85]:
## Feature representation
dim = 10

In [86]:
from tensorflow.keras.layers import Embedding, Input

model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [87]:

model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [88]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step


array([[[ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [-0.01276131, -0.00658168, -0.03984108,  0.01556703,
          0.04091363,  0.04965868, -0.00907396,  0.03175982,
          0.03606707, -0.02965554],
        [ 0.03520468, -0.02401367, -0.04095669, -0.02914996,
         -0.0492407 ,  0.02793998, -0.02839912,  0.01085953,
         -0.0439579 ,  0.00327723],
        [-0.01209509,  0.0312182 , -0.0479847 , -0.0

In [89]:
embedded_docs[0]

array([   0,    0,    0,    0, 7957, 3175, 1748, 2463])

In [90]:
import numpy as np

model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step


array([[[ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [ 0.04044672,  0.03817307, -0.00549127, -0.04541495,
          0.02205238, -0.02665005,  0.02596552, -0.00751743,
          0.00738063,  0.013214  ],
        [-0.01276131, -0.00658168, -0.03984108,  0.01556703,
          0.04091363,  0.04965868, -0.00907396,  0.03175982,
          0.03606707, -0.02965554],
        [ 0.03520468, -0.02401367, -0.04095669, -0.02914996,
         -0.0492407 ,  0.02793998, -0.02839912,  0.01085953,
         -0.0439579 ,  0.00327723],
        [-0.01209509,  0.0312182 , -0.0479847 , -0.0